version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Database (AWS RDS or External)
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      
      JWT_SECRET: ${JWT_SECRET:-mySecretKeyForJWTTokenGenerationThatIsLongEnoughForHS256Algorithm12345}
      
      # Using external remote Redis (e.g. Upstash)
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME:-default}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SSL: ${REDIS_SSL:-false}
      
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY:-}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY:-}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME:-task-manager-uploads}
      AWS_REGION: ${AWS_REGION:-ap-south-1}
      
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
